apiVersion: v1
kind: Service
metadata: 
  name: svc-pod
  labels:
    app: svc-app
spec: 
  selector:
    app: mypod-app
  type: LoadBalancer
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
